#!/usr/bin/env bash
# Shared helpers for ZimaOS and Unraid installers.

set -euo pipefail

STACK_NAME="mycelium-media-stack"
MYCELIUM_REPO="https://github.com/corveck79/mycelium.git"
MYCELIUM_IMAGE="ghcr.io/corveck79/mycelium:latest"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC} $*" >&2; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $*" >&2; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }
log_step()  { echo -e "${CYAN}==>${NC} $*" >&2; }

require_cmd() {
  local cmd
  for cmd in "$@"; do
    if ! command -v "$cmd" &>/dev/null; then
      log_error "Required command not found: ${cmd}"
      exit 1
    fi
  done
}

detect_host_ip() {
  local ip=""
  ip="$(hostname -I 2>/dev/null | awk '{print $1}')" || true
  if [[ -z "${ip}" ]]; then
    ip="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for (i=1;i<=NF;i++) if ($i=="src") {print $(i+1); exit}}')" || true
  fi
  if [[ -z "${ip}" ]]; then
    ip="127.0.0.1"
    log_warn "Could not detect LAN IP; using 127.0.0.1 for CATBOX_HOST. Update .env after install."
  fi
  echo "${ip}"
}

detect_puid_pgid() {
  local puid pgid
  puid="${PUID:-$(id -u)}"
  pgid="${PGID:-$(id -g)}"
  echo "${puid}:${pgid}"
}

random_secret() {
  if command -v openssl &>/dev/null; then
    openssl rand -hex 16
  else
    tr -dc 'a-f0-9' </dev/urandom | head -c 32
  fi
}

ensure_dir() {
  local dir="$1"
  mkdir -p "${dir}"
  chown -R "${PUID:-1000}:${PGID:-1000}" "${dir}" 2>/dev/null || true
}

download_spore_wrapper() {
  local dest_dir="$1"
  local wrapper="${dest_dir}/plex_transcoder_wrapper.sh"
  mkdir -p "${dest_dir}"
  curl -fsSL "https://raw.githubusercontent.com/corveck79/mycelium/main/spore/plex_transcoder_wrapper.sh" \
    -o "${wrapper}.upstream"
  # Upstream hardcodes 127.0.0.1; Plex runs in a separate container on bridge networks.
  sed 's|http://127.0.0.1:8088|http://mycelium:8088|g' "${wrapper}.upstream" > "${wrapper}"
  rm -f "${wrapper}.upstream"
  chmod +x "${wrapper}"
}

write_env_file() {
  local env_file="$1"
  local host_ip="$2"
  local webhook_secret="$3"

  if [[ -f "${env_file}" ]]; then
    log_warn "${env_file} already exists; leaving it untouched."
    return 0
  fi

  cat >"${env_file}" <<EOF
# Generated by ${STACK_NAME} installer on $(date -u +%Y-%m-%dT%H:%M:%SZ)
PUID=${PUID:-1000}
PGID=${PGID:-1000}
TZ=${TZ:-UTC}

# Required: paste keys before first use (or complete the Mycelium setup wizard).
TORBOX_API_KEY=${TORBOX_API_KEY:-replace-me}
TMDB_API_KEY=${TMDB_API_KEY:-replace-me}

# Mycelium / Catbox (lazy TorBox materialization — CatBox-style behavior)
CATBOX_MODE=true
CATBOX_HOST=http://${host_ip}:8088
CATBOX_IDLE_MINUTES=43200

# Mycelium Spore (Plex stub library)
SPORE_ENABLED=true
SPORE_MEDIA_PATH=/data/plex-media

# Optional Seerr integration (configure webhook after install)
SEERR_URL=http://seerr:5055
SEERR_API_KEY=

# Webhook secret for Seerr -> Mycelium
WEBHOOK_SECRET=${webhook_secret}

# Plex claim token (optional; expires in ~4 minutes) https://www.plex.tv/claim/
PLEX_CLAIM=${PLEX_CLAIM:-}

# Paths (installer sets these for your platform)
CONFIG_DIR=${CONFIG_DIR}
DATA_DIR=${DATA_DIR}

# Expose services on LAN (set false to bind localhost only)
EXPOSE_LAN=${EXPOSE_LAN:-true}

COMPOSE_PROJECT_NAME=${STACK_NAME}
EOF
}

write_compose_file() {
  local compose_file="$1"
  cat >"${compose_file}" <<'EOF'
# Mycelium + Spore + Plex + *arr stack
# Managed by install-zimaos.sh / install-unraid.sh

networks:
  media-network:
    driver: bridge

services:
  mycelium:
    image: ghcr.io/corveck79/mycelium:latest
    container_name: mycelium
    restart: unless-stopped
    networks:
      - media-network
    ports:
      - "${MYCELIUM_BIND:-0.0.0.0}:8088:8088"
    env_file:
      - .env
    environment:
      LISTEN_HOST: 0.0.0.0
      LISTEN_PORT: 8088
      MEDIA_PATH: /data/media
      DB_PATH: /data/requests.db
      SPORE_ENABLED: ${SPORE_ENABLED:-true}
      SPORE_MEDIA_PATH: ${SPORE_MEDIA_PATH:-/data/plex-media}
      CATBOX_MODE: ${CATBOX_MODE:-true}
      CATBOX_HOST: ${CATBOX_HOST}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      TORBOX_API_KEY: ${TORBOX_API_KEY}
      TMDB_API_KEY: ${TMDB_API_KEY}
      SEERR_URL: ${SEERR_URL:-}
      SEERR_API_KEY: ${SEERR_API_KEY:-}
    volumes:
      - ${DATA_DIR}/mycelium:/data
      - ${DATA_DIR}/plex-media:/data/plex-media
      - ${DATA_DIR}/spore:/spore:ro
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "44"
      - "109"
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request,sys; r=urllib.request.urlopen('http://127.0.0.1:8088/health',timeout=5); sys.exit(0 if r.status==200 else 1)",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 45s

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    networks:
      - media-network
    ports:
      - "${PLEX_BIND:-0.0.0.0}:32400:32400"
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-UTC}
      VERSION: docker
      PLEX_CLAIM: ${PLEX_CLAIM:-}
    depends_on:
      mycelium:
        condition: service_healthy
    volumes:
      - ${CONFIG_DIR}/plex:/config
      - ${DATA_DIR}/plex-media:/plex-media:ro
      - ${DATA_DIR}/spore:/spore:ro
    entrypoint:
      - /bin/sh
      - -c
      - |
        set -e
        if [ ! -f '/usr/lib/plexmediaserver/Plex Transcoder.real' ]; then
          mv '/usr/lib/plexmediaserver/Plex Transcoder' '/usr/lib/plexmediaserver/Plex Transcoder.real'
        fi
        cp /spore/plex_transcoder_wrapper.sh '/usr/lib/plexmediaserver/Plex Transcoder'
        chmod +x '/usr/lib/plexmediaserver/Plex Transcoder'
        exec /init

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    networks:
      - media-network
    ports:
      - "${PROWLARR_BIND:-0.0.0.0}:9696:9696"
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-UTC}
    volumes:
      - ${CONFIG_DIR}/prowlarr:/config
    depends_on:
      byparr:
        condition: service_started

  byparr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: byparr
    restart: unless-stopped
    networks:
      - media-network
    ports:
      - "${BYPARR_BIND:-0.0.0.0}:8191:8191"
    environment:
      LOG_LEVEL: info
      LOG_HTML: "false"
      TZ: ${TZ:-UTC}

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    networks:
      - media-network
    ports:
      - "${RADARR_BIND:-0.0.0.0}:7878:7878"
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-UTC}
    volumes:
      - ${CONFIG_DIR}/radarr:/config

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    networks:
      - media-network
    ports:
      - "${SONARR_BIND:-0.0.0.0}:8989:8989"
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-UTC}
    volumes:
      - ${CONFIG_DIR}/sonarr:/config

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    restart: unless-stopped
    networks:
      - media-network
    ports:
      - "${SEERR_BIND:-0.0.0.0}:5055:5055"
    environment:
      TZ: ${TZ:-UTC}
    volumes:
      - ${CONFIG_DIR}/seerr:/app/config
    depends_on:
      - plex
      - radarr
      - sonarr

EOF
}

apply_bind_addresses() {
  local env_file="$1"
  local expose_lan="${EXPOSE_LAN:-true}"
  local bind="0.0.0.0"
  if [[ "${expose_lan}" != "true" ]]; then
    bind="127.0.0.1"
  fi
  {
    echo "MYCELIUM_BIND=${bind}"
    echo "PLEX_BIND=${bind}"
    echo "PROWLARR_BIND=${bind}"
    echo "BYPARR_BIND=${bind}"
    echo "RADARR_BIND=${bind}"
    echo "SONARR_BIND=${bind}"
    echo "SEERR_BIND=${bind}"
  } >>"${env_file}"
}

print_post_install() {
  local install_dir="$1"
  local host_ip="$2"

  cat <<EOF

${GREEN}Install complete.${NC}

Install directory: ${install_dir}
Manage stack:      cd ${install_dir} && ./manage.sh <command>

Service URLs (LAN):
  Mycelium (setup):  http://${host_ip}:8088
  Plex:              http://${host_ip}:32400/web
  Seerr:             http://${host_ip}:5055
  Radarr:            http://${host_ip}:7878
  Sonarr:            http://${host_ip}:8989
  Prowlarr:          http://${host_ip}:9696

Next steps:
  1. Open Mycelium and finish the setup wizard (TorBox + TMDB keys, Catbox mode).
  2. Claim Plex (optional): export PLEX_CLAIM=... && ./manage.sh claim-plex && ./manage.sh restart plex
  3. In Plex, add a library pointing at /plex-media (Movies + TV).
  4. In Seerr: connect Plex, Radarr, Sonarr; set webhook to http://mycelium:8088/webhook
  5. In Mycelium Admin: add Radarr/Sonarr URLs for bulk import (not download clients).

Notes:
  - Mycelium handles grabs/streaming. Radarr/Sonarr are for bulk import + Seerr routing.
  - Spore is experimental; Linux/desktop Plex clients work best.
  - Only stream content you have the right to access.

EOF
}
