name: byparr

services:
  byparr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: byparr
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "8191:8191"
    environment:
      LOG_LEVEL: info
      LOG_HTML: "false"
      TZ: ${TZ:-UTC}
